'use strict';

const logger = require('../utils/logger');

// Event aggregation buffer: matchId -> { updates: Map(hash -> event), stateDiff: {} }
let buffer = new Map();
let intervalId = null;

// Batch config
const BATCH_INTERVAL_MS = 3000; // 3 seconds window

// List of completed batches for API/Dashboard observability
const completedBatches = [];

/**
 * Add events and state changes to the batch buffer.
 *
 * @param {string} matchId
 * @param {Array<object>} diffEvents - List of events generated by the diff engine
 * @param {object} stateDiff - Object containing modified fields (home_score, away_score, status, minute)
 */
function addEvents(matchId, diffEvents = [], stateDiff = {}) {
  if (!matchId) return;

  if (!buffer.has(matchId)) {
    buffer.set(matchId, {
      updates: new Map(),
      stateDiff: {}
    });
  }

  const matchBuffer = buffer.get(matchId);

  // 1. Add/deduplicate diff events by their hash
  diffEvents.forEach(ev => {
    if (ev.hash) {
      matchBuffer.updates.set(ev.hash, ev);
    }
  });

  // 2. Merge state diffs (preferring latest values)
  Object.assign(matchBuffer.stateDiff, stateDiff);
  
  logger.debug(`[Batch Aggregator] Buffered ${diffEvents.length} events and diffs for match ${matchId}`);
}

/**
 * Starts the micro-batch flush loop.
 */
function start() {
  if (intervalId) return;
  intervalId = setInterval(flush, BATCH_INTERVAL_MS);
  logger.info(`[Batch Aggregator] Real-time micro-batch loop started (interval: ${BATCH_INTERVAL_MS}ms)`);
}

/**
 * Stop loop.
 */
function stop() {
  if (intervalId) {
    clearInterval(intervalId);
    intervalId = null;
  }
}

/**
 * Flush all buffered events, aggregate them, and broadcast.
 */
function flush() {
  if (buffer.size === 0) return;

  const currentBuffer = buffer;
  buffer = new Map(); // swap buffer instantly to avoid race condition

  const batchesToBroadcast = [];

  for (const [matchId, matchData] of currentBuffer.entries()) {
    const updates = Array.from(matchData.updates.values());
    const stateDiff = matchData.stateDiff;

    // Only broadcast if there are actual updates or state changes
    if (updates.length > 0 || Object.keys(stateDiff).length > 0) {
      const payload = {
        match_id: matchId,
        updates,
        state_diff: stateDiff,
        timestamp: new Date().toISOString()
      };

      batchesToBroadcast.push(payload);
    }
  }

  if (batchesToBroadcast.length > 0) {
    const broadcaster = require('../realtime/broadcaster');
    batchesToBroadcast.forEach(batch => {
      logger.info(`[Batch Aggregator] Broadcasting packet for match ${batch.match_id}: ${batch.updates.length} events, diff: ${JSON.stringify(batch.state_diff)}`);
      
      // Trigger Supabase Realtime WebSocket Broadcast Channel
      broadcaster.broadcastMatchUpdate(batch.match_id, batch.updates, batch.state_diff).catch(err => {
        logger.error(`[Batch Aggregator] Realtime broadcast failed for match ${batch.match_id}: ${err.message}`);
      });
      
      // Store in memory list for dashboard ingestion console visualization
      completedBatches.push(batch);
      if (completedBatches.length > 50) {
        completedBatches.shift();
      }
    });
  }
}

/**
 * Retrieve recent completed batches.
 *
 * @returns {Array<object>}
 */
function getRecentBatches() {
  return completedBatches;
}

module.exports = {
  addEvents,
  start,
  stop,
  flush,
  getRecentBatches
};

